num1=input("Enter first number ")
num2=input("Enter second number ")
int(num1)
int(num2)
print(f"The sum of {num1} and {num2} is {int(num1+num2)}")
a = input("Enter your name ")
age=input("Enter you age ")
print(f"hello {a} you age is {age}")
